### ISSUE TITLE
Manual file

### ISSUE THREAD

**Issue by schpuntik** [bigtreetech/BIGTREETECH-S42B-V1.0#1]
Manual file is brocken. Please  upload again

**Comment by yangwenxiong** [comment]
> Manual file is brocken. Please upload again

Have been updated

**Comment by yangwenxiong** [comment]
[https://github.com/bigtreetech/BIGTREETECH-S42B-V1.0/issues/1#issue-546557873](url)

**Comment by yangwenxiong** [comment]
![WD0{J8~)B60 XK6 4@NJNP5](https://user-images.githubusercontent.com/46896566/71971896-90ffbc80-3246-11ea-8489-6b0180ac58e6.png)

**Comment by yangwenxiong** [comment]
![X()@{QMMW}GR~AW2HVHH5Y6](https://user-images.githubusercontent.com/46896566/71972463-a32e2a80-3247-11ea-9728-480b9e8d1a2e.png)

**Comment by yangwenxiong** [comment]
![$E3{ZKT9P7Z1}2E$7T_)ZWY](https://user-images.githubusercontent.com/46896566/71972802-66166800-3248-11ea-9c17-e81114513257.png)

**Comment by yangwenxiong** [comment]
![`@2CT9{)%{A0W5J)EJ6 07H](https://user-images.githubusercontent.com/46896566/71973083-f785da00-3248-11ea-93db-8e88d3fd414b.png)
