### ISSUE TITLE
Poor quality prints

### ISSUE THREAD

**Issue by megatech1966** [bigtreetech/BIGTREETECH-S42B-V1.0#32]
Hello all. I installed 2 BTT S42B V1 on to my x and y. Calibrated ok. Uncommented x and y in configuration.h. Y was playing up. Wasn’t moving all the way to 0 on my bed. Changed 2 lines in configuration_adv.h 
#define MINIMUM_STEPPER_PULSE 3

#define MAXIMUM_STEPPER_RATE 150000

Now y is working ok
Had to change x steps to 100 and y steps to 100

The problem is I get poor quality cube. Vertical banding and horrible ringing. The nice one was with my TMC2130s. 
My max acceleration is 500
Any help would be appreciated 😃
![BFBF4DDA-6EEC-45AF-AB52-3B24478832A9](https://user-images.githubusercontent.com/38471450/98367926-5e9d3680-2086-11eb-9ac2-ea68bffe48d8.jpeg)
![1704014B-7D16-40E0-BBC2-FCFD91A7553E](https://user-images.githubusercontent.com/38471450/98367946-68bf3500-2086-11eb-9c40-f500b84a4650.jpeg)
![F4635E30-5864-420D-B20A-E47CD32BCDB6](https://user-images.githubusercontent.com/38471450/98367963-71b00680-2086-11eb-81b3-ad42d5842624.jpeg)

**Comment by megatech1966** [comment]
![image](https://user-images.githubusercontent.com/38471450/98400023-48599f80-20b3-11eb-8487-d9960282bebb.jpeg)

S42B using open loop (switch 3 off)

**Comment by robtheminnie** [comment]
I have a similar issue with mine.  I have these fitted to x and y on an ender3, and now have the same ringing/vertical lines shown in the initial post.
Have you found a fix?

**Comment by megatech1966** [comment]
I updated the firmware from a fork of the btt firmware

**Comment by robtheminnie** [comment]
> I updated the firmware from a fork of the btt firmware

Do you have a link?

Was it from here?

https://github.com/bigtreetech/BIGTREETECH-Stepper-Motor-Driver/tree/0814d4a0371aa818ba08abeb214c3f460904cde9/S42B/firmware

**Comment by megatech1966** [comment]
https://github.com/swanepoeljan/TrueStep

**Comment by robtheminnie** [comment]
Ah, thanks.  Also, just seen you are using the V1.0 board.  I have V2.0 boards so that fork won't work unfortunately.
Thanks for the info though :) I might get in touch with the writer of that fork and see if he has any input.

**Comment by GIANNHSitia** [comment]
I have the same problem, have you found a solution? I have S42b 1.1 to X and Y axis

![Uploading IMG_20210214_191235.jpg…]()

**Comment by megatech1966** [comment]
I have a solution for version 1.0

**Comment by GIANNHSitia** [comment]
how to fix it?  not working to 1.1v?

**Comment by megatech1966** [comment]
This issue should be closed.
